from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from desktop_gremlin.game.models import GameMetadata, GameSave, TurnEvent


class GameRepository(Protocol):
    def create_game(self, save: GameSave) -> None: ...

    def load_game(self, game_id: str) -> GameSave: ...

    def save_game(self, save: GameSave) -> None: ...

    def list_games(self) -> list[GameMetadata]: ...

    def append_turn_event(self, event: TurnEvent) -> None: ...

    def list_turn_events(self, game_id: str) -> list[TurnEvent]: ...

    def recover_from_backup(self, game_id: str) -> GameSave: ...

    def commit_game_update(self, save: GameSave, update: Callable[[GameSave], None]) -> GameSave: ...
